- hosts: localhost
  roles:
     - {role: digitransit-azure-acs }
  vars:
     environment_type: PROD
     project_name: peatusee
     project: peatusee
     #How many master nodes defaults to 3 for HA
     master_nodes: 3
     #How many azure vms needs as nodes for DCOS
     agent_nodes: 6
     ssh_keys: /home/martivo/.ssh/id_rsa.pub
     admin_user: azureuser
