- hosts: localhost
  roles:
     - {role: digitransit-azure-appgw}
  vars: 
     environment_type: DEV
     project_name: peatusee
     project: peatusee
     certfile: /home/martivo/peatus/digitransit-mesos-deploy/self_signed_ssl/test.pfx
     certpass: fM2hkebDfcPq
     backend_servers: "peatusee-dev-acsagents.westeurope.cloudapp.azure.com"
